# Generated by Django 3.0.3 on 2020-02-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HexMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapTitle', models.CharField(max_length=50)),
                ('height', models.IntegerField(default=1000)),
                ('width', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexId', models.CharField(max_length=10)),
                ('col', models.CharField(max_length=4)),
                ('row', models.IntegerField(default=0)),
                ('tileType', models.CharField(default='Deep Water', max_length=50)),
                ('topBorderTile', models.CharField(max_length=10)),
                ('topBorderType', models.CharField(default='standard', max_length=30)),
                ('topRightBorderTile', models.CharField(max_length=10)),
                ('topRightBorderType', models.CharField(default='standard', max_length=30)),
                ('topLeftBorderTile', models.CharField(max_length=10)),
                ('topLeftBorderType', models.CharField(default='standard', max_length=30)),
                ('rightBorderTile', models.CharField(max_length=10)),
                ('rightBorderType', models.CharField(default='standard', max_length=30)),
                ('leftBorderTile', models.CharField(max_length=10)),
                ('leftBorderType', models.CharField(default='standard', max_length=30)),
                ('bottomLeftBorderTile', models.CharField(max_length=10)),
                ('bottomLeftBorderType', models.CharField(default='standard', max_length=30)),
                ('bottomRightBorderTile', models.CharField(max_length=10)),
                ('bottomRightBorderType', models.CharField(default='standard', max_length=30)),
                ('bottomBorderTile', models.CharField(max_length=10)),
                ('bottomBorderType', models.CharField(default='standard', max_length=30)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HexMap.HexMap')),
            ],
        ),
    ]
